version: '3'
services:

    sampler:
        build: . 
        image: shuntingyard/speedtest_sampler
        restart: always
        volumes:
          - /data:/data
          - /data/log:/var/log
        environment:
          - INTERVAL=600
          - CSVPATH=/data/speedtest.csv
          - LOGPATH=/var/log/sampler.log
