version: '3'
services:

    sampler:
        build: . 
        image: shuntingyard/speedtest_sampler
        restart: always
        volumes:
          - /var/lib/speedtest:/var/lib/speedtest
        environment:
          - INTERVAL=600
